### ISSUE TITLE
Empty energy cards after upgrade to HA 2023.6.0

### ISSUE THREAD

**Issue by jthun** [flixlix/energy-period-selector-plus#11]
**Describe the bug**
Hi, after upgrading to HA 2023.6.0, my energy cards on the same YAML page as the energy-period-selector-plus don't are empty/showing 0/showing errors that nothing could be calculated.

**To Reproduce**
1. Create a YAML page.
2. Add the following:
```
  - type: custom:energy-period-selector-plus
    compare_button_type: icon
    period_buttons:
      - day
      - week
      - month
      - year
      - custom
    custom_period_label: </|\>

  - type: energy-usage-graph

  - type: energy-distribution
    link_dashboard: false
```
3. See that all energy cards show empty, compare with standard energy dashboard.
4. Replace `type: custom:energy-period-selector-plus` with `type: energy-date-selection`, reload minimalist UI, go back to the root and then back to the page again (or just hard-refresh the page) and see how the energy cards now are filled with data.

**Expected behavior**
Data in the energy cards, as in HA 2023.5.0.

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [X] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/energy-period-selector-plus/discussions)).

- [X] I have the latest version of the card installed.

- [X] I have cleared my browser cache **after** installing, updating and configuring the card.

**Comment by jthun** [comment]
Hi,
I've removed the standard picker (not even commented out), but still have empty energy cards. No errors in the console.

Is my config ok? It has been working fine until the HA upgrade.

```
  - type: custom:energy-period-selector-plus
    compare_button_type: icon
    period_buttons:
      - day
      - week
      - month
      - year
      - custom
    custom_period_label: </|\>
```
